# Try to write a makefile for i.mx6ULL

CROSS_COMPILE=arm-none-eabi-

CC:=$(CROSS_COMPILE)gcc
LD:=$(CROSS_COMPILE)gcc 

OBJS:=

LDSCRIPT=target.ld 

OBJCOPY:=$(CROSS_COMPILE)objcopy 

CFLAGS:=

LDFLAGS:=


clean:
	rm -f *.bin 